image: node:lts-slim

pipelines:
  branches:
    master:
      - step:
          name: "Install dependcies"
          caches:
            - node
          script:
            - npm install --quiet
          artifacts:
            - node_modules/** # Save modules for next steps
      - parallel:
        - step:
              name: "Linting"
              script:
                - npm i -g @angular/cli
                - ng config -g cli.warnings.versionMismatch false
                - ng lint
        - step:
              name: "Build"
              script:
                - npm i -g @angular/cli
                - ng config -g cli.warnings.versionMismatch false
                - ng build --configuration production
              artifacts:
                - dist/**
      - step:
          name: "Deploy to Production"
          deployment: Production
          script:
            - pipe: atlassian/firebase-deploy:1.2.0
              variables:
                KEY_FILE: '$KEY_FILE'