# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: angular/ngcontainer:latest

pipelines:
  branches:
    master:
      - step:
          name: "install dependcies, build & deploy to production"
          deployment: production
          # caches:
          #   - docker
          #   - node
          script:
            - echo "only on master"
            - npm install --quiet
            - npm i -g @angular/cli
            - npm i -g firebase-tools
            - npm update
            - ng build --prod
            - firebase deploy --token "$FIREBASE_TOKEN"
