# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:dubnium-slim

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          name: "install dependcies, build & deploy to production"
          deployment: production
          script: # Modify the commands below to build your repository.
            - echo "only on master"
            - npm install --quiet
            - npm i -g @angular/cli
            - npm i -g firebase-tools
            - ng build --prod
            - firebase deploy --token "$FIREBASE_TOKEN"
