image: node:lts-slim

pipelines:
  branches:
    master:
      - step:
          name: "Install dependcies"
          caches:
            - node
          script:
            - npm install --quiet
            - npm i -g @angular/cli
            - npm i -g firebase-tools
          artifacts:
            - node_modules/** # Save modules for next steps
      - parallel:
        - step:
            name: "Build"
            script:
              - ng config -g cli.warnings.versionMismatch false
              - ng build --configuration production
            artifacts:
              - dist/**
        - step:
            name: "Linting"
            script:
              - ng lint
      - step:
          name: "Deploy to Production"
          deployment: Production
          script:
            - firebase deploy --token "$FIREBASE_TOKEN"