# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: bartholomej/angular-firebase

pipelines:
  default:
    - step:
        name: install dependcies
        caches:
          - node
        script: 
          - npm install
          - npm update
    - step:
        name: build for production
        caches:
          - node
        script: 
          - ng build --prod
    - step:
        name: deployment to production
        caches:
          - node
        script: 
          - firebase deploy --token "$FIREBASE_TOKEN"


