# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:lts-slim

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          name: "Install dependcies"
          script:
            - npm install --quiet
            - npm i -g @angular/cli
            - npm i -g firebase-tools
      - parallel:
        - step:
          caches:
            - node
          name: "Build"
          script:
            - ng config -g cli.warnings.versionMismatch false
            - ng build --configuration production
          artifacts:
            - dist/changekraft/**
        - step:
          caches:
            - node
          name: "Linting"
          script:
            - ng lint
      - step:
          caches:
            - node
          name: "Deploy to Production"
          deployment: Production
          script:
            - firebase deploy --token "$FIREBASE_TOKEN"
