import { Injectable } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';

@Injectable()
export class IconsClass {
  constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer) {
    iconRegistry.addSvgIcon(
      'account_circle',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-account_circle-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'autorenew',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-autorenew-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'block',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-block-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'check',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-check-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'account_circle_outline',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/outline-account_circle-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'commute',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-commute-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'delete',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-delete_forever-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'directions',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-directions-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'edit',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-edit-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'email',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-email-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'event',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-event_note-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'home',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-home-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'hotel',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-hotel-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'invitation',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-insert_invitation-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'local_dining',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-local_dining-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'location_on',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-location_on-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'lock_open',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-lock_open-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'lock',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-lock-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'loyalty',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-loyalty-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'menu',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-menu-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'more_vert',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-more_vert-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'save',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-save-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'supervisor_account',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-supervisor_account-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'supervisor_account_outline',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/outline-supervisor_account-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'visibility_off',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-visibility_off-24px.svg'
      )
    );
    iconRegistry.addSvgIcon(
      'visibility',
      sanitizer.bypassSecurityTrustResourceUrl(
        'assets/fonts/material-icons/svg/baseline-visibility-24px.svg'
      )
    );
  }
}
