import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  MatToolbarModule,
  MatButtonModule,
  MatSidenavModule,
  MatIconModule,
  MatListModule,
  MatGridListModule,
  MatCardModule,
  MatMenuModule,
  MatTableModule,
  MatPaginatorModule,
  MatSortModule,
  MatInputModule,
  MatNativeDateModule,
  MatSlideToggleModule,
  MatStepperModule,
  MatFormFieldModule,
  MatCheckboxModule,
  MatRadioModule,
  MatExpansionModule,
  MatBadgeModule,
  MatSliderModule,
  MatSelectModule,
  MatDatepickerModule,
  MatSnackBarModule,
  MatProgressBarModule,
  MatDividerModule,
  MatTabsModule
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatRadioModule,
    MatExpansionModule,
    MatBadgeModule,
    MatSliderModule,
    MatSnackBarModule,
    MatSelectModule,
    MatDatepickerModule,
    MatProgressBarModule,
    MatDividerModule,
    MatTabsModule
  ],
  exports: [
    CommonModule,
    MatToolbarModule,
    MatButtonModule,
    MatNativeDateModule,
    MatSidenavModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatMenuModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatFormFieldModule,
    MatCheckboxModule,
    MatRadioModule,
    MatExpansionModule,
    MatBadgeModule,
    MatSliderModule,
    MatSnackBarModule,
    MatSelectModule,
    MatDatepickerModule,
    MatProgressBarModule,
    MatDividerModule,
    MatTabsModule
  ]
})
export class MaterialModule {}
